<?php

declare(strict_types=1);

namespace App\Tests\Api\Catalog;

use App\Catalog\Domain\ObjectKind;
use App\Catalog\Domain\Repository\ObjectTypeRepositoryInterface;
use App\Shared\Domain\Tenant;
use Doctrine\DBAL\Connection;
use PHPUnit\Framework\Attributes\Test;

use const JSON_THROW_ON_ERROR;

/**
 * HARD-05 — cursor pagination on `/api/products/{id}/audit-log`.
 *
 * Audit rows are inserted directly via DBAL so the test bypasses the
 * DH Auditor subscriber + DAMADoctrineTestBundle's rolled-back
 * transaction (the SELECT in the controller would not otherwise see
 * the rows the subscriber inserted in the same transaction). The
 * direct insert is purely a fixture concern; the controller path
 * under test is unchanged.
 */
final class AuditLogPaginationApiTest extends CatalogApiTestCase
{
    /**
     * dh_auditor.yaml intentionally excludes CatalogObject from
     * audited entities (data mutations interleave with the search
     * indexer + Mercure publisher in ways the bundle does not yet
     * handle cleanly — see the YAML comment). The dev DB carries an
     * `objects_audit` left over from an earlier config and the
     * /api/products/{id}/audit-log endpoint queries it directly.
     *
     * Materialise a minimal version of that table in the test DB so
     * pagination behaviour can be exercised end-to-end without
     * depending on the bundle's flush listener. Schema mirrors
     * `attributes_audit` (the bundle's standard layout), see
     * AuditLogTest::auditTableCarriesTheBundleSchema.
     */
    private function ensureObjectsAuditTable(Connection $conn): void
    {
        $conn->executeStatement(<<<'SQL'
            CREATE TABLE IF NOT EXISTS objects_audit (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                type VARCHAR(10) NOT NULL,
                object_id VARCHAR(255) NOT NULL,
                discriminator VARCHAR(255),
                transaction_hash VARCHAR(40),
                diffs JSON,
                blame_id VARCHAR(255),
                blame_user VARCHAR(255),
                blame_user_fqdn VARCHAR(255),
                blame_user_firewall VARCHAR(100),
                ip VARCHAR(45),
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
            )
            SQL);
    }

    #[Test]
    public function paginatesAuditEntriesViaCursor(): void
    {
        $client = $this->authenticatedClient();
        $tenant = $this->em()->getRepository(Tenant::class)->findOneBy(['code' => self::TENANT_CODE]);
        \assert($tenant instanceof Tenant);

        $productType = self::getContainer()
            ->get(ObjectTypeRepositoryInterface::class)
            ->findBuiltInByKind(ObjectKind::Product, $tenant);
        \assert(null !== $productType);

        $created = $client->request('POST', '/api/products', [
            'headers' => ['content-type' => 'application/ld+json'],
            'body' => json_encode([
                'code' => 'AUDIT-PAGINATION',
                'objectTypeId' => $productType->getId()->toRfc4122(),
            ], JSON_THROW_ON_ERROR),
        ])->toArray();
        $productId = $created['id'] ?? null;
        \assert(\is_string($productId));

        // Seed 25 deterministic audit rows. Direct DBAL INSERT keeps
        // the rows visible to the controller's SELECT inside the same
        // rolled-back transaction.
        /** @var Connection $conn */
        $conn = self::getContainer()->get(Connection::class);
        $this->ensureObjectsAuditTable($conn);
        for ($i = 0; $i < 25; ++$i) {
            $conn->insert('objects_audit', [
                'type' => 'update',
                'object_id' => $productId,
                'discriminator' => null,
                'transaction_hash' => sprintf('hash%02d', $i),
                'diffs' => json_encode(['attributes' => ['name' => sprintf('v%02d', $i)]], JSON_THROW_ON_ERROR),
                'blame_id' => null,
                'blame_user' => 'tester',
                'blame_user_fqdn' => null,
                'blame_user_firewall' => null,
                'ip' => null,
                // Distinct timestamps — newer index = newer row.
                'created_at' => sprintf('2026-05-12 10:%02d:00', $i),
            ]);
        }

        // Page 1: limit=10. Expect the 10 newest rows + a next_cursor.
        $page1 = $client->request('GET', '/api/products/'.$productId.'/audit-log?limit=10')->toArray();
        $entries1 = $page1['entries'] ?? [];
        \assert(\is_array($entries1));
        self::assertCount(10, $entries1);
        $firstCursor = $page1['next_cursor'] ?? null;
        \assert(\is_string($firstCursor));
        $first1 = $entries1[0];
        \assert(\is_array($first1));
        self::assertSame('2026-05-12 10:24:00', $first1['created_at']);

        // Page 2: cursor + same limit. Expect the next 10 rows, no
        // overlap with page 1, fresh next_cursor.
        $page2 = $client
            ->request('GET', '/api/products/'.$productId.'/audit-log?limit=10&cursor='.urlencode($firstCursor))
            ->toArray();
        $entries2 = $page2['entries'] ?? [];
        \assert(\is_array($entries2));
        self::assertCount(10, $entries2);
        $secondCursor = $page2['next_cursor'] ?? null;
        \assert(\is_string($secondCursor));
        $first2 = $entries2[0];
        \assert(\is_array($first2));
        self::assertSame('2026-05-12 10:14:00', $first2['created_at']);

        $stamps1 = array_map(
            static fn (mixed $e): string => \is_array($e) && \is_string($e['created_at'] ?? null)
                ? $e['created_at']
                : '',
            $entries1,
        );
        $stamps2 = array_map(
            static fn (mixed $e): string => \is_array($e) && \is_string($e['created_at'] ?? null)
                ? $e['created_at']
                : '',
            $entries2,
        );
        self::assertEmpty(array_intersect($stamps1, $stamps2), 'pages 1 and 2 must not overlap.');

        // Page 3: cursor again. Only 5 rows left → next_cursor must be null.
        $page3 = $client
            ->request('GET', '/api/products/'.$productId.'/audit-log?limit=10&cursor='.urlencode($secondCursor))
            ->toArray();
        $entries3 = $page3['entries'] ?? [];
        \assert(\is_array($entries3));
        self::assertCount(5, $entries3);
        self::assertArrayHasKey('next_cursor', $page3);
        self::assertNull($page3['next_cursor']);
    }

    #[Test]
    public function gibberishCursorFallsBackToFirstPage(): void
    {
        $client = $this->authenticatedClient();
        $tenant = $this->em()->getRepository(Tenant::class)->findOneBy(['code' => self::TENANT_CODE]);
        \assert($tenant instanceof Tenant);

        $productType = self::getContainer()
            ->get(ObjectTypeRepositoryInterface::class)
            ->findBuiltInByKind(ObjectKind::Product, $tenant);
        \assert(null !== $productType);

        $created = $client->request('POST', '/api/products', [
            'headers' => ['content-type' => 'application/ld+json'],
            'body' => json_encode([
                'code' => 'AUDIT-GIBBERISH-CURSOR',
                'objectTypeId' => $productType->getId()->toRfc4122(),
            ], JSON_THROW_ON_ERROR),
        ])->toArray();
        $productId = $created['id'] ?? null;
        \assert(\is_string($productId));

        /** @var Connection $conn */
        $conn = self::getContainer()->get(Connection::class);
        $this->ensureObjectsAuditTable($conn);

        $response = $client->request(
            'GET',
            '/api/products/'.$productId.'/audit-log?cursor=@@@invalid@@@',
        );
        self::assertResponseIsSuccessful();
        $body = $response->toArray();
        // No audit rows for this fresh product → empty page, no error.
        self::assertSame([], $body['entries'] ?? null);
        self::assertArrayHasKey('next_cursor', $body);
        self::assertNull($body['next_cursor']);
    }
}
