<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * GOLIVE #2177 (cold-start L7) — own `messenger_messages` in migrations.
 *
 * No migration ever created the Doctrine transport table: it existed on the
 * operator's machine only because Messenger's auto-setup ran BEFORE the
 * W1-1 role split, when the runtime role still had DDL rights. On a fresh
 * install the `failed` transport's auto-setup issues CREATE TABLE as
 * `pim_app` (non-owner, no DDL by design) -> "permission denied for schema
 * public" -> the worker crashloops from first boot.
 *
 * DDL below is byte-for-byte what `messenger:setup-transports` produces on
 * PostgreSQL 16 (captured empirically from a scratch database, 2026-07-04;
 * this doctrine-messenger version creates no LISTEN/NOTIFY trigger — the
 * consumer polls). Infra table: NO tenant_id, NO RLS, same class as
 * doctrine_migration_versions (see Version20260428195217 docblock).
 *
 * Explicit grants are belt-and-braces: W1-1 default privileges already
 * cover owner-created tables, but a pg_restore drops them (known quirk),
 * so the grant is repeated here to keep the table self-contained.
 *
 * `IF NOT EXISTS` keeps the migration green on every environment where
 * auto-setup already created the table (operator dev, CI).
 */
final class Version20260704050000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create messenger_messages (Doctrine transport) with pim_app grants — fresh installs no longer depend on auto-setup DDL the runtime role cannot execute';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        // Same composite index auto-setup creates (queue polling path); the
        // hashed name is what DBAL derives for these columns — kept verbatim
        // so a table created either way is schema-identical.
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('GRANT SELECT, INSERT, UPDATE, DELETE ON messenger_messages TO pim_app');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS messenger_messages');
    }
}
