<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * VIEW-06 (#418) — DH Auditor table for ChannelObjectTypeMapping. Tracks
 * `target_field` and `is_published` mutations on per-(Channel × ObjectType
 * × Attribute) mapping rows. Schema mirrors the other audit tables
 * (channels_audit, attributes_audit, …): one row per write op, with
 * blame metadata + a JSON `diffs` payload.
 */
final class Version20260504094746 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'VIEW-06: add channel_object_type_mappings_audit table (DH Auditor)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE channel_object_type_mappings_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_df7c70f7c71d121f0fb9ad22180d3f74_idx ON channel_object_type_mappings_audit (type)');
        $this->addSql('CREATE INDEX object_id_df7c70f7c71d121f0fb9ad22180d3f74_idx ON channel_object_type_mappings_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_df7c70f7c71d121f0fb9ad22180d3f74_idx ON channel_object_type_mappings_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_df7c70f7c71d121f0fb9ad22180d3f74_idx ON channel_object_type_mappings_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_df7c70f7c71d121f0fb9ad22180d3f74_idx ON channel_object_type_mappings_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_df7c70f7c71d121f0fb9ad22180d3f74_idx ON channel_object_type_mappings_audit (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE channel_object_type_mappings_audit');
    }
}
