<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Epic 0.11 / ticket #99 — DH Auditor audit-log tables.
 *
 * Per-entity tables (`<entity>_audit`) hold every insert / update /
 * remove / association event the bundle observes. Operators consume
 * the rows through the future "History" tab on show pages and through
 * `pim:audit:cleanup` for retention pruning.
 *
 * Configured entities: Catalog (CatalogObject, ObjectValue, ObjectType,
 * Attribute, AttributeGroup, AttributeOption, Association,
 * AssociationType), Channel, Asset, Identity (User, Role, Permission,
 * Tenant), API Configurator (ApiProfile, ApiKey).
 */
final class Version20260430092112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'DH Auditor audit-log tables for Catalog/Channel/Asset/Identity/ApiConfigurator (#99).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_keys_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_719856506729acfa99f02d4099f42961_idx ON api_keys_audit (type)');
        $this->addSql('CREATE INDEX object_id_719856506729acfa99f02d4099f42961_idx ON api_keys_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_719856506729acfa99f02d4099f42961_idx ON api_keys_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_719856506729acfa99f02d4099f42961_idx ON api_keys_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_719856506729acfa99f02d4099f42961_idx ON api_keys_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_719856506729acfa99f02d4099f42961_idx ON api_keys_audit (created_at)');
        $this->addSql('CREATE TABLE api_profiles_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_aa097e8f95a79d18480d240811bf1a28_idx ON api_profiles_audit (type)');
        $this->addSql('CREATE INDEX object_id_aa097e8f95a79d18480d240811bf1a28_idx ON api_profiles_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_aa097e8f95a79d18480d240811bf1a28_idx ON api_profiles_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_aa097e8f95a79d18480d240811bf1a28_idx ON api_profiles_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_aa097e8f95a79d18480d240811bf1a28_idx ON api_profiles_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_aa097e8f95a79d18480d240811bf1a28_idx ON api_profiles_audit (created_at)');
        $this->addSql('CREATE TABLE assets_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_5a2d89edf121ec59e2826702465104ed_idx ON assets_audit (type)');
        $this->addSql('CREATE INDEX object_id_5a2d89edf121ec59e2826702465104ed_idx ON assets_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_5a2d89edf121ec59e2826702465104ed_idx ON assets_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_5a2d89edf121ec59e2826702465104ed_idx ON assets_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_5a2d89edf121ec59e2826702465104ed_idx ON assets_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_5a2d89edf121ec59e2826702465104ed_idx ON assets_audit (created_at)');
        $this->addSql('CREATE TABLE association_types_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_15e401fd023a7e6fcfcefc0ee8f1e222_idx ON association_types_audit (type)');
        $this->addSql('CREATE INDEX object_id_15e401fd023a7e6fcfcefc0ee8f1e222_idx ON association_types_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_15e401fd023a7e6fcfcefc0ee8f1e222_idx ON association_types_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_15e401fd023a7e6fcfcefc0ee8f1e222_idx ON association_types_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_15e401fd023a7e6fcfcefc0ee8f1e222_idx ON association_types_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_15e401fd023a7e6fcfcefc0ee8f1e222_idx ON association_types_audit (created_at)');
        $this->addSql('CREATE TABLE attribute_groups_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_852c9bc6380d5a03341044ab22fd3a4f_idx ON attribute_groups_audit (type)');
        $this->addSql('CREATE INDEX object_id_852c9bc6380d5a03341044ab22fd3a4f_idx ON attribute_groups_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_852c9bc6380d5a03341044ab22fd3a4f_idx ON attribute_groups_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_852c9bc6380d5a03341044ab22fd3a4f_idx ON attribute_groups_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_852c9bc6380d5a03341044ab22fd3a4f_idx ON attribute_groups_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_852c9bc6380d5a03341044ab22fd3a4f_idx ON attribute_groups_audit (created_at)');
        $this->addSql('CREATE TABLE attribute_options_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_7182dc8e986647874a63b8053d797430_idx ON attribute_options_audit (type)');
        $this->addSql('CREATE INDEX object_id_7182dc8e986647874a63b8053d797430_idx ON attribute_options_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_7182dc8e986647874a63b8053d797430_idx ON attribute_options_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_7182dc8e986647874a63b8053d797430_idx ON attribute_options_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_7182dc8e986647874a63b8053d797430_idx ON attribute_options_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_7182dc8e986647874a63b8053d797430_idx ON attribute_options_audit (created_at)');
        $this->addSql('CREATE TABLE attributes_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_5e40a2b203259112082f1eb184494bf9_idx ON attributes_audit (type)');
        $this->addSql('CREATE INDEX object_id_5e40a2b203259112082f1eb184494bf9_idx ON attributes_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_5e40a2b203259112082f1eb184494bf9_idx ON attributes_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_5e40a2b203259112082f1eb184494bf9_idx ON attributes_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_5e40a2b203259112082f1eb184494bf9_idx ON attributes_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_5e40a2b203259112082f1eb184494bf9_idx ON attributes_audit (created_at)');
        $this->addSql('CREATE TABLE channels_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_b0b8bae9424f90edf24698cdf4903097_idx ON channels_audit (type)');
        $this->addSql('CREATE INDEX object_id_b0b8bae9424f90edf24698cdf4903097_idx ON channels_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_b0b8bae9424f90edf24698cdf4903097_idx ON channels_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_b0b8bae9424f90edf24698cdf4903097_idx ON channels_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_b0b8bae9424f90edf24698cdf4903097_idx ON channels_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_b0b8bae9424f90edf24698cdf4903097_idx ON channels_audit (created_at)');
        $this->addSql('CREATE TABLE object_associations_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_13c1ddcdf1de39202c32ccab4fb7e473_idx ON object_associations_audit (type)');
        $this->addSql('CREATE INDEX object_id_13c1ddcdf1de39202c32ccab4fb7e473_idx ON object_associations_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_13c1ddcdf1de39202c32ccab4fb7e473_idx ON object_associations_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_13c1ddcdf1de39202c32ccab4fb7e473_idx ON object_associations_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_13c1ddcdf1de39202c32ccab4fb7e473_idx ON object_associations_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_13c1ddcdf1de39202c32ccab4fb7e473_idx ON object_associations_audit (created_at)');
        $this->addSql('CREATE TABLE object_types_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_6584b177845d0899f2197aa406f90052_idx ON object_types_audit (type)');
        $this->addSql('CREATE INDEX object_id_6584b177845d0899f2197aa406f90052_idx ON object_types_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_6584b177845d0899f2197aa406f90052_idx ON object_types_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_6584b177845d0899f2197aa406f90052_idx ON object_types_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_6584b177845d0899f2197aa406f90052_idx ON object_types_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_6584b177845d0899f2197aa406f90052_idx ON object_types_audit (created_at)');
        $this->addSql('CREATE TABLE object_values_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_a6878f901a233980203536a71ad690fe_idx ON object_values_audit (type)');
        $this->addSql('CREATE INDEX object_id_a6878f901a233980203536a71ad690fe_idx ON object_values_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a6878f901a233980203536a71ad690fe_idx ON object_values_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a6878f901a233980203536a71ad690fe_idx ON object_values_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a6878f901a233980203536a71ad690fe_idx ON object_values_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a6878f901a233980203536a71ad690fe_idx ON object_values_audit (created_at)');
        $this->addSql('CREATE TABLE objects_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_b2d7e494aa78f534f3dbedf67b811e34_idx ON objects_audit (type)');
        $this->addSql('CREATE INDEX object_id_b2d7e494aa78f534f3dbedf67b811e34_idx ON objects_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_b2d7e494aa78f534f3dbedf67b811e34_idx ON objects_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_b2d7e494aa78f534f3dbedf67b811e34_idx ON objects_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_b2d7e494aa78f534f3dbedf67b811e34_idx ON objects_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_b2d7e494aa78f534f3dbedf67b811e34_idx ON objects_audit (created_at)');
        $this->addSql('CREATE TABLE permissions_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_12ea9c690a467e489b437249dfbb2123_idx ON permissions_audit (type)');
        $this->addSql('CREATE INDEX object_id_12ea9c690a467e489b437249dfbb2123_idx ON permissions_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_12ea9c690a467e489b437249dfbb2123_idx ON permissions_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_12ea9c690a467e489b437249dfbb2123_idx ON permissions_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_12ea9c690a467e489b437249dfbb2123_idx ON permissions_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_12ea9c690a467e489b437249dfbb2123_idx ON permissions_audit (created_at)');
        $this->addSql('CREATE TABLE roles_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_a388815a9caf9918acd1b79cf22b5096_idx ON roles_audit (type)');
        $this->addSql('CREATE INDEX object_id_a388815a9caf9918acd1b79cf22b5096_idx ON roles_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a388815a9caf9918acd1b79cf22b5096_idx ON roles_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a388815a9caf9918acd1b79cf22b5096_idx ON roles_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a388815a9caf9918acd1b79cf22b5096_idx ON roles_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a388815a9caf9918acd1b79cf22b5096_idx ON roles_audit (created_at)');
        $this->addSql('CREATE TABLE tenants_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_305c4972653be6a8a7227185fdae58e3_idx ON tenants_audit (type)');
        $this->addSql('CREATE INDEX object_id_305c4972653be6a8a7227185fdae58e3_idx ON tenants_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_305c4972653be6a8a7227185fdae58e3_idx ON tenants_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_305c4972653be6a8a7227185fdae58e3_idx ON tenants_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_305c4972653be6a8a7227185fdae58e3_idx ON tenants_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_305c4972653be6a8a7227185fdae58e3_idx ON tenants_audit (created_at)');
        $this->addSql('CREATE TABLE users_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_5d977da36e91813e766863f2f579043a_idx ON users_audit (type)');
        $this->addSql('CREATE INDEX object_id_5d977da36e91813e766863f2f579043a_idx ON users_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_5d977da36e91813e766863f2f579043a_idx ON users_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_5d977da36e91813e766863f2f579043a_idx ON users_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_5d977da36e91813e766863f2f579043a_idx ON users_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_5d977da36e91813e766863f2f579043a_idx ON users_audit (created_at)');
        $this->addSql('DROP TABLE processed_messages');
        $this->addSql('ALTER TABLE assets DROP CONSTRAINT assets_object_fk');
        $this->addSql('ALTER INDEX association_types_tenant_idx RENAME TO IDX_2E181B5D9033212A');
        $this->addSql('ALTER INDEX attribute_groups_tenant_idx RENAME TO IDX_D28C172A9033212A');
        $this->addSql('ALTER INDEX attribute_options_attribute_idx RENAME TO IDX_5BA9A343B6E62EFA');
        $this->addSql('ALTER INDEX attributes_tenant_idx RENAME TO IDX_319B9E709033212A');
        $this->addSql('ALTER INDEX attributes_group_idx RENAME TO IDX_319B9E70FE54D947');
        $this->addSql('ALTER INDEX channel_object_type_mappings_attribute_idx RENAME TO IDX_904F75C9B6E62EFA');
        $this->addSql('ALTER TABLE channels DROP CONSTRAINT channels_category_root_fk');
        $this->addSql('DROP INDEX channels_category_tree_root_idx');
        $this->addSql('ALTER INDEX channel_locales_channel_idx RENAME TO IDX_52D86BBA72F5A1AA');
        $this->addSql('ALTER INDEX channel_locales_locale_idx RENAME TO IDX_52D86BBAE559DFD1');
        $this->addSql('ALTER INDEX channel_currencies_channel_idx RENAME TO IDX_810D160572F5A1AA');
        $this->addSql('ALTER INDEX channel_currencies_currency_idx RENAME TO IDX_810D160538248176');
        $this->addSql('ALTER INDEX object_associations_source_idx RENAME TO IDX_6E5B4DD64BB3C5E5');
        $this->addSql('ALTER INDEX object_associations_type_idx RENAME TO IDX_6E5B4DD6C54C8C93');
        $this->addSql('ALTER INDEX object_type_attributes_object_type_idx RENAME TO IDX_3B912E37C5020C33');
        $this->addSql('ALTER INDEX object_type_attributes_attribute_idx RENAME TO IDX_3B912E37B6E62EFA');
        $this->addSql('ALTER INDEX object_types_tenant_idx RENAME TO IDX_DD13DDD29033212A');
        $this->addSql('ALTER INDEX object_types_label_attribute_idx RENAME TO IDX_DD13DDD2E2D3A503');
        $this->addSql('ALTER INDEX object_types_image_attribute_idx RENAME TO IDX_DD13DDD2BC295696');
        $this->addSql('DROP INDEX objects_path_gist_idx');
        $this->addSql('DROP INDEX objects_attributes_indexed_gin');
        $this->addSql('DROP INDEX objects_path_btree_idx');
        $this->addSql('ALTER INDEX objects_tenant_idx RENAME TO IDX_B21ACCF39033212A');
        $this->addSql('ALTER INDEX objects_object_type_idx RENAME TO IDX_B21ACCF3C5020C33');
        $this->addSql('ALTER INDEX objects_parent_idx RENAME TO IDX_B21ACCF3727ACA70');
        $this->addSql('ALTER TABLE refresh_tokens DROP CONSTRAINT refresh_tokens_user_fk');
        $this->addSql('ALTER TABLE refresh_tokens DROP CONSTRAINT refresh_tokens_tenant_fk');
        $this->addSql('ALTER INDEX role_permissions_role_idx RENAME TO IDX_1FBA94E6D60322AC');
        $this->addSql('ALTER INDEX role_permissions_permission_idx RENAME TO IDX_1FBA94E6FED90CCA');
        $this->addSql('ALTER INDEX user_roles_user_idx RENAME TO IDX_54FCD59FA76ED395');
        $this->addSql('ALTER INDEX user_roles_role_idx RENAME TO IDX_54FCD59FD60322AC');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE processed_messages (message_id UUID NOT NULL, handler_class VARCHAR(255) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (message_id))');
        $this->addSql('CREATE INDEX processed_messages_handler_idx ON processed_messages (handler_class)');
        $this->addSql('CREATE INDEX processed_messages_processed_at_idx ON processed_messages (processed_at)');
        $this->addSql('DROP TABLE api_keys_audit');
        $this->addSql('DROP TABLE api_profiles_audit');
        $this->addSql('DROP TABLE assets_audit');
        $this->addSql('DROP TABLE association_types_audit');
        $this->addSql('DROP TABLE attribute_groups_audit');
        $this->addSql('DROP TABLE attribute_options_audit');
        $this->addSql('DROP TABLE attributes_audit');
        $this->addSql('DROP TABLE channels_audit');
        $this->addSql('DROP TABLE object_associations_audit');
        $this->addSql('DROP TABLE object_types_audit');
        $this->addSql('DROP TABLE object_values_audit');
        $this->addSql('DROP TABLE objects_audit');
        $this->addSql('DROP TABLE permissions_audit');
        $this->addSql('DROP TABLE roles_audit');
        $this->addSql('DROP TABLE tenants_audit');
        $this->addSql('DROP TABLE users_audit');
        $this->addSql('ALTER TABLE assets ADD CONSTRAINT assets_object_fk FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_2e181b5d9033212a RENAME TO association_types_tenant_idx');
        $this->addSql('ALTER INDEX idx_d28c172a9033212a RENAME TO attribute_groups_tenant_idx');
        $this->addSql('ALTER INDEX idx_5ba9a343b6e62efa RENAME TO attribute_options_attribute_idx');
        $this->addSql('ALTER INDEX idx_319b9e709033212a RENAME TO attributes_tenant_idx');
        $this->addSql('ALTER INDEX idx_319b9e70fe54d947 RENAME TO attributes_group_idx');
        $this->addSql('ALTER INDEX idx_810d160538248176 RENAME TO channel_currencies_currency_idx');
        $this->addSql('ALTER INDEX idx_810d160572f5a1aa RENAME TO channel_currencies_channel_idx');
        $this->addSql('ALTER INDEX idx_52d86bbae559dfd1 RENAME TO channel_locales_locale_idx');
        $this->addSql('ALTER INDEX idx_52d86bba72f5a1aa RENAME TO channel_locales_channel_idx');
        $this->addSql('ALTER INDEX idx_904f75c9b6e62efa RENAME TO channel_object_type_mappings_attribute_idx');
        $this->addSql('ALTER TABLE channels ADD CONSTRAINT channels_category_root_fk FOREIGN KEY (category_tree_root_object_id) REFERENCES objects (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX channels_category_tree_root_idx ON channels (category_tree_root_object_id)');
        $this->addSql('ALTER INDEX idx_6e5b4dd6c54c8c93 RENAME TO object_associations_type_idx');
        $this->addSql('ALTER INDEX idx_6e5b4dd64bb3c5e5 RENAME TO object_associations_source_idx');
        $this->addSql('ALTER INDEX idx_3b912e37c5020c33 RENAME TO object_type_attributes_object_type_idx');
        $this->addSql('ALTER INDEX idx_3b912e37b6e62efa RENAME TO object_type_attributes_attribute_idx');
        $this->addSql('ALTER INDEX idx_dd13ddd29033212a RENAME TO object_types_tenant_idx');
        $this->addSql('ALTER INDEX idx_dd13ddd2e2d3a503 RENAME TO object_types_label_attribute_idx');
        $this->addSql('ALTER INDEX idx_dd13ddd2bc295696 RENAME TO object_types_image_attribute_idx');
        $this->addSql('CREATE INDEX objects_path_gist_idx ON objects (path) WHERE ((kind)::text = \'category\'::text)');
        $this->addSql('CREATE INDEX objects_attributes_indexed_gin ON objects (attributes_indexed)');
        $this->addSql('CREATE INDEX objects_path_btree_idx ON objects (path) WHERE ((kind)::text = \'category\'::text)');
        $this->addSql('ALTER INDEX idx_b21accf39033212a RENAME TO objects_tenant_idx');
        $this->addSql('ALTER INDEX idx_b21accf3727aca70 RENAME TO objects_parent_idx');
        $this->addSql('ALTER INDEX idx_b21accf3c5020c33 RENAME TO objects_object_type_idx');
        $this->addSql('ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_1fba94e6fed90cca RENAME TO role_permissions_permission_idx');
        $this->addSql('ALTER INDEX idx_1fba94e6d60322ac RENAME TO role_permissions_role_idx');
        $this->addSql('ALTER INDEX idx_54fcd59fd60322ac RENAME TO user_roles_role_idx');
        $this->addSql('ALTER INDEX idx_54fcd59fa76ed395 RENAME TO user_roles_user_idx');
    }
}
