<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * AUD-DATA-003 (#3019) — make migrations the sole owner of DH Auditor DDL.
 *
 * Three audited entities were added after the original audit-table migration.
 * Development resets happened to create their tables through
 * `audit:schema:update --force`, while tenant provisioning and deployment only
 * ran migrations. The resulting schema depended on which operational path had
 * created the database.
 *
 * IF NOT EXISTS is intentional: databases previously reset through the old
 * path already contain these tables. The JSONB conversion brings both those
 * databases and migration-only fresh installs to the fixed point reported by
 * `audit:schema:update --dump-sql`.
 */
final class Version20260826211500 extends AbstractMigration
{
    /**
     * Hashes are generated by DH Auditor 6.3 for its deterministic index
     * names. Keeping them identical makes the bundle's read-only schema dump
     * empty after migrations.
     *
     * @var array<string, string>
     */
    private const array MISSING_AUDIT_TABLES = [
        'backups_audit' => '05323a79cdd3bf3124d29170d0063fa4',
        'import_profiles_audit' => '9678a32845ba43f89a7f450462357998',
        'import_sessions_audit' => '25aaa9e80cdf25b74bf3dd7829f7f318',
    ];

    /** @var list<string> */
    private const array ACTIVE_AUDIT_TABLES = [
        'api_keys_audit',
        'api_profiles_audit',
        'assets_audit',
        'attribute_groups_audit',
        'attribute_options_audit',
        'attributes_audit',
        'backups_audit',
        'channels_audit',
        'import_profiles_audit',
        'import_sessions_audit',
        'object_types_audit',
        'permissions_audit',
        'roles_audit',
        'tenants_audit',
        'users_audit',
    ];

    public function getDescription(): string
    {
        return 'AUD-DATA-003: move all active DH Auditor tables into migrations and normalize diffs to JSONB (#3019).';
    }

    public function up(Schema $schema): void
    {
        foreach (self::MISSING_AUDIT_TABLES as $table => $hash) {
            $this->addSql(<<<SQL
                CREATE TABLE IF NOT EXISTS {$table} (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    type VARCHAR(10) NOT NULL,
                    object_id VARCHAR(255) NOT NULL,
                    discriminator VARCHAR(255) DEFAULT NULL,
                    transaction_hash VARCHAR(40) DEFAULT NULL,
                    diffs JSONB DEFAULT NULL,
                    blame_id VARCHAR(255) DEFAULT NULL,
                    blame_user VARCHAR(255) DEFAULT NULL,
                    blame_user_fqdn VARCHAR(255) DEFAULT NULL,
                    blame_user_firewall VARCHAR(100) DEFAULT NULL,
                    ip VARCHAR(45) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    PRIMARY KEY (id)
                )
                SQL);

            foreach (['type', 'object_id', 'discriminator', 'transaction_hash', 'blame_id', 'created_at'] as $column) {
                $this->addSql("CREATE INDEX IF NOT EXISTS {$column}_{$hash}_idx ON {$table} ({$column})");
            }
        }

        foreach (self::ACTIVE_AUDIT_TABLES as $table) {
            $this->addSql("ALTER TABLE {$table} ALTER COLUMN diffs TYPE JSONB USING diffs::jsonb");
        }

        // Version20260818120000 used IF NOT EXISTS for a new partial index,
        // but a fresh install still had the older non-partial index from
        // Version20260428131449. Upgraded databases (where that index had once
        // been removed) and fresh databases therefore reached two different
        // schemas. Recreate it explicitly so the contract has one fixed point.
        $this->addSql('DROP INDEX IF EXISTS tenants_domain_uniq');
        $this->addSql(
            'CREATE UNIQUE INDEX tenants_domain_uniq ON tenants (domain) WHERE domain IS NOT NULL',
        );
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            true,
            'Audit-schema takeover is intentionally irreversible: an older database may already have contained the three tables. Restore the pre-migration backup instead.',
        );
    }
}
