<?php

declare(strict_types=1);

namespace App\Export\Catalog\Domain\Enum;

/**
 * Catalog profile lifecycle status (ADR-0027, CPDF-P1-01). `paused` catalogs
 * are not regenerated by the scheduler; `error` marks a catalog whose last
 * regeneration failed.
 */
enum CatalogStatus: string
{
    case Active = 'active';
    case Paused = 'paused';
    case Error = 'error';
}
