<?php

declare(strict_types=1);

namespace App\Export\Feed\Domain\Enum;

/**
 * Feed lifecycle status (ADR-0023, XMLF-P1-01). `paused` feeds are not
 * regenerated by the scheduler; `error` marks a feed whose last regeneration
 * failed (e.g. a required slot is unmapped).
 */
enum FeedStatus: string
{
    case Active = 'active';
    case Paused = 'paused';
    case Error = 'error';
}
